# disabled because OpenSSH is installed
# change to NO_START=0 to enable Dropbear
NO_START=0

# Dropbear Default Port
DROPBEAR_PORT=143

# Additional arguments:
# -p 109  : port utama SSH (digunakan HAProxy backend ssh)
# -p 143  : port alternatif SSH
# -b      : banner file
# -I 60   : idle timeout 60 detik
# -E      : log ke stderr
DROPBEAR_EXTRA_ARGS="-b /etc/banner.txt -p 109 -p 143 -I 60 -E"

# Banner file
DROPBEAR_BANNER="/etc/banner.txt"

# RSA hostkey file (default: /etc/dropbear/dropbear_rsa_host_key)
#DROPBEAR_RSAKEY="/etc/dropbear/dropbear_rsa_host_key"

# DSS hostkey file (default: /etc/dropbear/dropbear_dss_host_key)
#DROPBEAR_DSSKEY="/etc/dropbear/dropbear_dss_host_key"

# ECDSA hostkey file (default: /etc/dropbear/dropbear_ecdsa_host_key)
#DROPBEAR_ECDSAKEY="/etc/dropbear/dropbear_ecdsa_host_key"

# Receive window size
DROPBEAR_RECEIVE_WINDOW=65536
